# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

Scheme = "iOSPackageDemo"
Workspace = "iOSPackageDemo.xcworkspace"

def updateProjectBuildNumber

  currentTime = Time.new.strftime("%m-%d-%H:%M:%S")
  build = "#{currentTime}"
  puts("*************| 更新build #{build} |*************")
  # => 更改项目 build 号
  increment_build_number(build_number: build)

end 

platform :ios do
  lane :qa do |options|
    desc "QA环境构建"
    updateProjectBuildNumber
    package(export_method: "ad-hoc", configuration: "QA", options: options)
  end

  lane :enterprise do |options|
    desc "企业签环境构建"
    package(export_method: "ad-hoc", configuration: "Enterprise", options: options)
  end

  lane :super do |options|
    desc "超级签环境构建"
    package(export_method: "ad-hoc", configuration: "Super", options: options)
  end

  lane :tf do
    desc "TF签环境构建"
    package(export_method: "app-store", configuration: "TestFlight")
  end

  lane :uploadToTF do
      desc "发送到TestFlight"
      upload_to_testflight(
        username: "",
        app_identifier: "",
        skip_submission:true,
        ipa:""
      )
  end

  lane :package do |params|
    # 导出配置
    options = params[:options]
    export_options = nil
    if options[:app_url] && options[:display_image_url] && options[:full_size_image_url]
      export_options = {
        manifest: {
          appURL: options[:app_url],
          displayImageURL: options[:display_image_url],
          fullSizeImageURL: options[:full_size_image_url]
        }
      }
    end

    gym(
      scheme: "#{Scheme}",
      workspace: "#{Workspace}",
      include_bitcode: false,
      export_method: params[:export_method],
      configuration: params[:configuration],
      export_options: export_options
    )
  end
end